### ISSUE TITLE
New forge 1.14.4-28.0.45 version errors on startup

### ISSUE THREAD

**Issue by Tntmister** [Olafski/FastLeafDecay#22]
In forge versions before 1.14.4-28.0.45, the mod could be used in 1.14.4, but with the new forge version that changed how TickEvents work, the mod stopped being compatible

**Comment by SDPhantom** [comment]
Crash Log:
> [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: fastleafdecay, class net.olafkeijsers.fastleafdecay.FastLeafDecay
java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent
	at net.olafkeijsers.fastleafdecay.FastLeafDecay.<init>(FastLeafDecay.java:38) ~[?:v16]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) [?:28.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$1998/307307754.accept(Unknown Source) [?:28.0]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$1997/110932276.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$1997/110932276.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:133) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2089/1415761574.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:102) ~[modlauncher-3.2.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	... 25 more

**Comment by raziel23x** [comment]
![image](https://user-images.githubusercontent.com/441966/62588285-33300880-b893-11e9-87f9-24f515b634a4.png)

**Comment by bloodconfetti** [comment]
[latest.log](https://github.com/Olafski/FastLeafDecay/files/3484814/latest.log)

**Comment by ProsperCraft** [comment]
Same It used to work for 1.14.4 until forge made a breaking change so it no longer works with .45

[debug.log](https://github.com/Olafski/FastLeafDecay/files/3485013/debug.log)
[latest.log](https://github.com/Olafski/FastLeafDecay/files/3485014/latest.log)

**Comment by Ommina** [comment]
See https://github.com/MinecraftForge/MinecraftForge/commit/1af7b7603d72eea7d5b4de5fd7c1a0f800258ffe

**Comment by Olafski** [comment]
Thanks for the reports everyone! I have been on holiday for the past two weeks and just got back, so I'll get to work. :)

**Comment by Olafski** [comment]
I have to say, it's quite annoying to have to keep up with all the refactors Forge does all the time. But this takes the cake, within a minor MC version they change the loader in a non-backwards compatible way. Now I have to push out two 1.14.4 versions and people on CurseForge will never be able to tell which one to use...

**Comment by bloodconfetti** [comment]
:/ Yeah I'm so sorry... It's really ruined a lot of people's weeks I think.

Hope your holiday was good! Thank you for even thinking about an attempt at dealing with this mess!

**Comment by Olafski** [comment]
Well, it should be fixed in version 17, let's see how this goes. I tried my best to make the issue apparent on the description...

**Comment by raziel23x** [comment]
yep forge is breaking the loader/api every other build they have been doing here lately its a annoying
