### ISSUE TITLE
Could not load during server start

### ISSUE THREAD

**Issue by jasminnancy** [Olafski/FastLeafDecay#53]
I've been using FastLeafDecay for years! Running 1.17.1 on paper.
I just updated to lastest release and now get this on server start:

```
[15:27:25] [Server thread/ERROR]: Could not load 'plugins/FastLeafDecay-26.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[patched_1.17.1.jar:git-Paper-100]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:160) ~[patched_1.17.1.jar:git-Paper-100]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.17.1.jar:git-Paper-100]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:276) ~[patched_1.17.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-100]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-100]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 7 more
```

**Comment by Olafski** [comment]
Hey Jasminnancy, thanks for reporting this.

If I read this log correctly, it looks like you're using bukkit. FastLeafDecay is a Forge plugin, does Bukkit run those? :$ I'm not very well versed in other loaders so I'm not sure.

**Comment by NZScruffy** [comment]
I get the same issue... i guess this plugin no longer works for paper.

**Comment by Olafski** [comment]
As i said in the previous comment, this is a forge mod, not a plugin for paper or bukkit. I'm surprised it worked at all...
